# /action.yml
name: 'hello action'
description: 'add actions'
inputs:
  token:
    description: 'GITHUB_TOKEN'
    default: ${{ github.token }}
  
    
runs:
  using: 'docker'
  image: Dockerfile
  env:
    TOKEN: ${{ inputs.token }}
